apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ttc.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "ttc.name" . }}
    helm.sh/chart: {{ include "ttc.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  nginx.conf: |
    server {
      listen 8080 default_server;
      listen [::]:8080 default_server;

      location / {
        return 200;
      }

      location /ttc/ {
          proxy_pass http://localhost:5000/;
          auth_basic "ttc application";
          auth_basic_user_file "/etc/nginx/htpasswd";
      }
    }
  config.json: |
    {
      "ttc": {
        "stops": {{ toJson .Values.ttcStops }}
      },
      "weather": {
        "coordinates": {{ .Values.weatherCoordinates | quote }}
      }
    }
