apiVersion: v1
kind: Service
metadata:
  name: {{ include "ttc.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "ttc.name" . }}
    helm.sh/chart: {{ include "ttc.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort:  8080
      protocol: TCP
      name: http-8080
  selector:
    app.kubernetes.io/name: {{ include "ttc.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
